version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: finance_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



  finance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance_api
    ports:
      - "8080:8080"
    env_file:
      - .env.example
    depends_on:
      - postgres

volumes:
  postgres_data: